language: php

php:
  - 5.4
  - 5.5
  - hhvm

services:
  - elasticsearch

env:
  global:
    - PLUGIN_NAME=ElasticsearchSource
    - PLUGIN_PATH=Plugin/ElasticsearchSource
    - REQUIRE="imsamurai/cakephp-environment:dev-master phpdocumentor/phpdocumentor:2.*"
    - DB=mysql
    - CAKE_VERSION=2.4
    - secure: gJVq4HkCVB3UZ/f9aBjCqT9IsOby4Ze9N67bp4BXOLcLDeWnpAOfbi85F0HATxXcuQA5A55UOFWqHFYXigVQ2J3w6Um3jseGCUi4ssh09u0orksDzem5OzulPVaJltiM5LC7d9GgSQDVaN5nDAIfP+bZE4SDIWUpwftO0xTuaSY=
  matrix:
    - CAKE_VERSION=2.3
    - CAKE_VERSION=2.4
    - CAKE_VERSION=2.5

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1
    - php: 5.5
      env:
        - PHPDOC=1

before_install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.12.deb && sudo dpkg -i elasticsearch-0.90.12.deb && sudo service elasticsearch restart

before_script:
    - chmod +x ./travis/*
    - ./travis/before_script.sh
    - if [ "$PHPCS" != 1 ]; then
            echo "
                CakePlugin::load('HttpSource', array('bootstrap' => true, 'routes' => false));
                CakePlugin::load('ElasticsearchSource');
            " >> ../cakephp/app/Config/bootstrap.php;
            echo "<?php
                class DATABASE_CONFIG {
                    public \$elasticsearchTest = array(
                        'datasource' => 'ElasticsearchSource.Http/ElasticsearchSource',
                        'host' => 'localhost',
                        'prefix' => '',
                        'port' => 9200,
                        'timeout' => 5
                    );
                    public \$test = array(
                        'datasource' => 'Database/Mysql',
                        'host' => '127.0.0.1',
                        'login' => 'travis',
                        'database' => 'test',
                        'prefix' => '',
                        'encoding' => 'utf8'
                    );
                }" > ../cakephp/app/Config/database.php;
      fi

script:
  - cat ../cakephp/app/Config/database.php
  - ./travis/script.sh

after_success:
  - ./travis/after_success.sh

notifications:
  email: im.samuray@gmail.com