language: php

php:
  - 5.4
  - 5.5
  - hhvm

services:
  - elasticsearch

env:
  global:
    - PLUGIN_NAME=ElasticsearchSource
    - PLUGIN_PATH=Plugin/ElasticsearchSource
    - REQUIRE="imsamurai/cakephp-environment:dev-master phpdocumentor/phpdocumentor:2.*"
    - DB=mysql
    - CAKE_VERSION=2.4
    - secure: QLBWSmCnBYGYxvMu6dZLHr4k7nNbWI/dvj0pWjFmMamUsylorCGG3krh8b7CGOa94+zJJkJmRw6O8zQj2ge/WnRiSU4eUY0cD5e0zutD4GtzJEq2mXNu7o55yLbVGrXSj36jDnZV4+1WvUV5nWTN+bZMFga3GzQuI5WUReHr8WY=
  matrix:
    - CAKE_VERSION=2.3
    - CAKE_VERSION=2.4
    - CAKE_VERSION=2.5

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1
    - php: 5.5
      env:
        - PHPDOC=1

before_install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.1.deb && sudo dpkg -i elasticsearch-1.4.1.deb && sudo service elasticsearch restart

before_script:
  - git clone git://github.com/imsamurai/travis-plugin-build.git --depth 1 travis
  - chmod +x ./travis/*
  - ./travis/before_script.sh
  - if [ "$PHPCS" != 1 ]; then
        echo "
            CakePlugin::load('HttpSource', array('bootstrap' => true, 'routes' => true));
            CakePlugin::load('ElasticsearchSource', array('bootstrap' => false, 'routes' => true));
        " >> ../cakephp/app/Config/bootstrap.php;
        mv ../cakephp/app/Config/database.php ../cakephp/app/Config/database-default.php;
        cat ../cakephp/app/Config/database-default.php | sed "s/class DATABASE_CONFIG {/class DATABASE_CONFIG extends DB_CONFIG {/" > ../cakephp/app/Config/database.php;
        echo "class DB_CONFIG {
                public \$elasticsearchTest = array(
                    'datasource' => 'ElasticsearchSource.Http/ElasticsearchSource',
                    'host' => 'localhost',
                    'prefix' => '',
                    'port' => 9200,
                    'timeout' => 5
                );
            }" >> ../cakephp/app/Config/database.php;
        echo "<?php
            require_once dirname(dirname(__FILE__)) . '/vendor/autoload.php';
            require_once dirname(dirname(dirname(__FILE__))) . '/lib/Cake/Console/ShellDispatcher.php';
            return ShellDispatcher::run(\$argv);
        " > ../cakephp/app/Console/cake.php;
        echo "Configure::write('debug', 0);" >> ../cakephp/app/Config/core.php;
        curl -XGET '127.0.0.1:9200' -vvvv;
        curl -XPUT '127.0.0.1:9200/test_index';
    fi;

script:
  - ./travis/script.sh

after_success:
  - ./travis/after_success.sh

notifications:
  email: im.samuray@gmail.com