language: php

php:
  - 5.4
  - 5.5

services:
  - elasticsearch

env:
  global:
    - PLUGIN_NAME=ElasticsearchSource
    - PLUGIN_PATH=Plugin/ElasticsearchSource
    - REQUIRE=""
    - DB=mysql
    - CAKE_VERSION=2.4
  matrix:
    - CAKE_VERSION=2.3
    - CAKE_VERSION=2.4
    - CAKE_VERSION=master

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1

before_install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.12.deb && sudo dpkg -i elasticsearch-0.90.12.deb && sudo service elasticsearch restart

before_script:
    - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
    - ../travis/before_script.sh
    - if [ "$PHPCS" != 1 ]; then
            echo "
                CakePlugin::load('HttpSource', array('bootstrap' => true, 'routes' => false));
                CakePlugin::load('ElasticsearchSource');
            " >> ../cakephp/app/Config/bootstrap.php;
            echo "<?php
                class DATABASE_CONFIG {
                    public \$elasticsearchTest = array(
                        'datasource' => 'ElasticsearchSource.Http/ElasticsearchSource',
                        'host' => 'localhost',
                        'prefix' => '',
                        'port' => 9200,
                        'timeout' => 5
                    );
                    public \$test = array(
                        'datasource' => 'Database/Mysql',
                        'host' => '127.0.0.1',
                        'login' => 'travis',
                        'database' => 'test',
                        'prefix' => '',
                        'encoding' => 'utf8'
                    );
                }" > ../cakephp/app/Config/database.php;
      fi
    - if [ "$PHPCS" = 1 ]; then
        rm -rf ~/.phpenv/versions/$(phpenv version-name)/pear/PHP/CodeSniffer/Standards/CakePHP;
        git clone https://github.com/imsamurai/cakephp-codesniffer.git --depth 1 ~/.phpenv/versions/$(phpenv version-name)/pear/PHP/CodeSniffer/Standards/CakePHP;
      fi
    - curl -XGET '127.0.0.1:9200' -vvvv
    - curl -XPUT '127.0.0.1:9200/test_index'

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: im.samuray@gmail.com